### ISSUE TITLE
SwipeItem suggestions

### ISSUE THREAD

**Issue by lixuanle** [computerjazz/react-native-swipeable-item#1]
Just copy-pasting this from the other thread:

- Support for swiping in both directions; currently your package only supports swiping left or right. Correct me if I'm wrong though.

- A parameter for allowing swiping all the way but if the user lets go, it'll snap back and stay open depending on the underlayWidth value.

- A function to programmatically close rows. For example, if I interact with another row I want to be able to call a closeRow() function on the other rows.

- A callback to keep track of the X value that is being animated for each row. Stemming off my 2nd suggestion, I'd like to be able to keep track of how far the user has swiped, and if it has passed a certain X value then I would remove the row from the list.

Thanks again for doing this.

**Comment by computerjazz** [comment]
>Support for swiping in both directions; currently your package only supports swiping left or right. Correct me if I'm wrong though.

Just to clarify, you'd like "up"/"down" yeah? Sounds good.

>A parameter for allowing swiping all the way but if the user lets go, it'll snap back and stay open depending on the underlayWidth value.

Not sure I understand, does it not stay open currently when you swipe the whole width?

>A function to programmatically close rows. For example, if I interact with another row I want to be able to call a closeRow() function on the other rows.

If you grab a ref to an Item you can call `itemRef.close()` or `itemRef.open()` on it: https://github.com/computerjazz/react-native-swipeable-item/blob/master/index.tsx#L94-L97

I was trying to figure out whether there was a better way to expose this, but didn't come up with anything (I didn't want to do anything too complex like using render props). Would be open to suggestions.

>A callback to keep track of the X value that is being animated for each row. Stemming off my 2nd suggestion, I'd like to be able to keep track of how far the user has swiped, and if it has passed a certain X value then I would remove the row from the list.

This might be expensive if not throttled, but possible.

All good ideas, thanks for the input!

**Comment by lixuanle** [comment]
> Just to clarify, you'd like "up"/"down" yeah? Sounds good.

Up/down sounds good too, but I meant allowing swipe to go both left **and** right. So for example a use case would be swiping left to delete, while swiping right can be for sending a message. Kind of how gmail works on mobile.

> Not sure I understand, does it not stay open currently when you swipe the whole width?

Currently, I'm unable to swipe past whatever value I have set to `underlayWidth`. The slider locks once it's at whatever value you set and does not open any further. Something like this is what I'm looking to be able to do: https://streamable.com/ucgrh

So if `underlayWidth` is set to `75`, then the slider stays open at 75, but I want to be able to open all the way and have it snap back to the `underlayWidth` value. If this is already the way it works, let me know; I probably messed up somewhere trying to implement it into my project.

> If you grab a ref to an Item you can call itemRef.close() or itemRef.open() on it: https://github.com/computerjazz/react-native-swipeable-item/blob/master/index.tsx#L94-L97
Will add to README

Perfect, this is exactly what I needed thanks!

> This might be expensive if not throttled, but possible.

No problem, was just looking for a way so that I could implement both swiping all the way to remove a row, or press a button such as in your example.

**Comment by computerjazz** [comment]
I've got some changes up and running for the bi-directional swipe and the overSwipe-with-springback. There are some breaking api changes, but since this project is a day old and I think you're the only one using it I'm not planning on obeying semver just yet -- heads up! 😅

Will post here when published.

**Comment by computerjazz** [comment]
Ok published 1.0.3 with breaking api changes, but added the features I mentioned above. Let me know how it feels!

Question for you -- currently the `underlayLeft` prop's signature is `() => React.ReactNode`, which means that in order to access the FlatList `item`, it needs to be inlined within `renderItem`.  Do you think it would be a nicer api to pass data _into_ the SwipeRow, and then send it back in the `underlayLeft` and `underlayRight` methods so those could be extracted into class methods/external callbacks?

Here's how it is now:
```js
renderItem = ({ item }) => (
  <SwipeItem
    underlayLeft={() => (
      <TouchableOpacity onPress={() => this.doSomethingWithItem(item)} /> // <- Accessing `item` requires us to inline 
  )}
  />
)
```

Here's how it could be:

```js
underlayLeft = (item) =>  <TouchableOpacity onPress={() => this.doSomethingWithItem(item)} />

renderItem = ({ item }) => (
  <SwipeItem
    item={item} // <- would require passing item into SwipeItem
    underlayLeft={this.underlayLeft}
  />
)
```

**Comment by lixuanle** [comment]
Can confirm swiping in both left **and** right work using `underlayWidthRight` and `underlayWidthLeft`. `underlayRight` and `underlayLeft` also work to render the component behind.

Yea, I think the 2nd one would be nicer just to give users the option of being able sent data into the underlay methods. I don't see a problem with it at all, and it allows for more flexibility.

**Comment by lixuanle** [comment]
Is there anyway to have 2 different versions of `onChange`?

Currently `onChange` is triggered whether or not the swipe is fully swiped. So if your `underlayWidthLeft` is set to 300, but you only swipe to a width of 10, `onChange` will be called.

Can you make it so there is a function for when the swipe is fully open, and then also another function that keeps part of the current functionality where it knows if the swipe is partially open?

I'm currently trying to implement swiping to delete the row, but if the user only swipes a little bit the delete function is being called when I only want it to be called if the row is opened all the way.

**Comment by computerjazz** [comment]
Hey so I made a few more changes -- the underlay component now receives a `percentOpen` animated value that you should be able to trigger delete based on.
So if you want to call your delete function when it's half-open (percent > 0.5) it might look like like:

```js
<Animated.Code>
  {() => block([
    cond(greaterThan(percentOpen, .5), call([percentOpen], () => this.delete(item)))
  ])}
</Animated.Code>
```

**Comment by computerjazz** [comment]
I think all the suggestions have been addressed -- thanks for the ideas! Feel free to open a new issue if you think of anything else.
