### ISSUE TITLE
Function trigger with overswipe

### ISSUE THREAD

**Issue by dancixx** [computerjazz/react-native-swipeable-item#11]
Hi, 

first of all, your package is awesome, but i have a question. Is there any option, for example to trigger a deletefunction with overswipe. I use the draggable flatlist and i need full swipe delete and delete to tap.

Thank for answer.
Regards, Daniel

**Comment by computerjazz** [comment]
You can set a snap point at the point you want to trigger delete and then listen for that point in `onChange`.
Here's a quick and dirty example:

```tsx
<SwipeableItem
  item={props.item}
  snapPointsRight={[0, 100, Dimensions.get("window").width]}
  onChange={({ snapPoint }) => {
    if (snapPoint === Dimensions.get("window").width) {
      alert("delete!");
    }
  }}
  renderUnderlayRight={() => <View />}
  renderOverlay={() => <RowItem {...props} />}
/>
```

![swipe-to-del](https://user-images.githubusercontent.com/6730148/87972493-d3b71280-ca7b-11ea-94ae-6db6b93ce57f.gif)

**Comment by Karthik-B-06** [comment]
@computerjazz I think this should be documented. I was searching for this solution. Great library man! 🎉
