### ISSUE TITLE
Animated: 'useNativeDriver' was not specified

### ISSUE THREAD

**Issue by AndriyGord** [computerjazz/react-native-swipeable-item#13]
Hello. Thank you for you amazing work.  Everything work fine, except a warning as I mentioned in the title. On every swipe I have warning:  Animated: `useNativeDriver` was not specified. This is a required 'option and must be explicitly set to `true` or `false`

**Comment by computerjazz** [comment]
This is a warning from react-native Animated, but this package uses reanimated exclusively, so I can't see how it would be responsible. Are you triggering other animations on swipe?

**Comment by AndriyGord** [comment]
Thank you for the tip. I'll check it
