### ISSUE TITLE
Reanimated get value error

### ISSUE THREAD

**Issue by jesselurie** [computerjazz/react-native-swipeable-item#14]
Hi, thank you for building this great package. Im working with the React Native Draggable FlatList in conjunction with React Native Swipeable Item for IOS. I ran the React Native Draggable FlatList without the swappable item and this didn't occur.  

**Describe the bug**
What  I'm encountering is when running the example in the readme of React Native Swipeable Item The first initial boot is fine but then on subsequence saves or re render the following happens.

Warning: Please report: Excessive number of pending callbacks: 501. Some pending callbacks that might have leaked by never being called from native code: {"15183":{"module":"ReanimatedModule","method":"getValue"},"15186":{"module":"ReanimatedModule","method":"getValue"},"15203":{"module":"ReanimatedModule","method":"getValue"},"15221":{"module":"ReanimatedModule","method":"getValue"},"15240":{"module":"ReanimatedModule","method":"getValue"},"15259":{"module":"ReanimatedModule","method":"getValue"},"15286":{"module":"ReanimatedModule","method":"getValue"},"15320":{"module":"ReanimatedModule","method":"getValue"},"15323":{"module":"ReanimatedModule","method":"getValue"},"15326":{"module":"ReanimatedModule","method":"getValue"},"15329":{"module":"ReanimatedModule","method":"getValue"},"15332":{"module":"ReanimatedModule","method":"getValue"},"15335":{"module":"ReanimatedModule","method":"getValue"},"15338":{"module":"ReanimatedModule","method":"getValue"},"15341":{"module":"ReanimatedModule","method":"getValue"},"15360":{"module":"ReanimatedModule","method":"getValue"},"15363":{"module":"ReanimatedModule","method":"getValue"},"15366":{"module":"ReanimatedModule","method":"getValue"},"15369":{"module":"ReanimatedModule","method":"getValue"},"15372":{"module":"ReanimatedModule","method":"getValue"},"15375":{"module":"ReanimatedModule","method":"getValue"},"15436":{"module":"ReanimatedModule","method":"getValue"},"15474":{"module":"ReanimatedModule","method":"getValue"},"15480":{"module":"ReanimatedModule","method":"getValue"},"15483":{"module":"ReanimatedModule","method":"getValue"},"15490":{"module":"ReanimatedModule","method":"getValue"},"15498":{"module":"ReanimatedModule","method":"getValue"},"15509":{},"15523":{"module":"ReanimatedModule","method":"getValue"},"15541":{},"15560":{"module":"ReanimatedModule","method":"getValue"},"15573":{"module":"ReanimatedModule","method":"getValue"},"15594":{"module":"ReanimatedModule","method":"getValue"},"15603":{"module":"ReanimatedModule","method":"getValue"},"15631":{"module":"ReanimatedModule","method":"getValue"},"15639":{"module":"ReanimatedModule","method":"getValue"},"15656":{},"15674":{"module":"ReanimatedModule","method":"getValue"},"15684":{"module":"ReanimatedModule","method":"getValue"},"15688":{"module":"ReanimatedModule","method":"getValue"},"15691":{"module":"ReanimatedModule","method":"getValue"},"15694":{"module":"ReanimatedModule","method":"getValue"},"15713":{"module":"ReanimatedModule","method":"getValue"},"15724":{"module":"ReanimatedModule","method":"getValue"},"15728":{"module":"ReanimatedModule","method":"getValue"},"15734":{"module":"ReanimatedModule","method":"getValue"},"15738":{"module":"ReanimatedModule","method":"getValue"},"15744":{"module":"ReanimatedModule","method":"getValue"},"15748":{"module":"ReanimatedModule","method":"getValue"},"15755":{"module":"ReanimatedModule","method":"getValue"},"...(truncated keys)...":451} 

**Steps to reproduce the behavior:**
To reproduce this just copy and paste the code from the readme example. 
Run the code and then upon additional save (re render) the error will appear.

**Platform & Dependencies**
Please list any applicable dependencies in addition to those below (react-navigation etc).
"@react-navigation/drawer": "^5.8.5",
"@react-navigation/native": "^5.7.0",
"@react-navigation/stack": "^5.7.0",

Platform (iOS/Android):
 React Native or Expo version: React native  "^0.63.1" 
`react-native-reanimated` version:      "^1.10.1",
`react-native-gesture-handler` version:     "^1.7.0",

**Additional context**

**Comment by Manu206** [comment]
I have the same issue but also for initial render :(

**Comment by binchik** [comment]
I'm having the same issue. @jesselurie did you come up with a solution?

**Comment by SvenJonsson** [comment]
We have this as well. Also in combination with react-native-draggable-flatlist.

**Comment by hengkx** [comment]
same issue

**Comment by Fortidude** [comment]
Same issue here. Looks like it's just a warning, but I'm not sure why, how and what is causing it. And if this is a big issue or not.

For now I didn't notice any issue because of that on production (both iOS and android)

**Comment by worldlee78** [comment]
I am also getting this on a SectionList that uses react-native-swipeable-item that renders about 300 items. From what I've read it seems to be a known issue with large numbers of Reanimated components rendering on a page. They didn't seem to have a solution for it and it doesn't seem to affect render speeds in production. But if anyone has any advice on how to avoid causing this error I'd be very interested.

**Comment by anthlasserre** [comment]
Just get this error too when using `{ percentOpen }` in `<Animated.View style={{ opacity: percentOpen }}>`.
I temporary fixed this issue by calling **Animated** from `react-native-animated` and not from `react-native`.
Don't know if it is the best solution but it works 🔥

**Comment by worldlee78** [comment]
> Just get this error too when using `{ percentOpen }` in `<Animated.View style={{ opacity: percentOpen }}>`.
> I temporary fixed this issue by calling **Animated** from `react-native-animated` and not from `react-native`.
> Don't know if it is the best solution but it works 🔥

I'm not sure I understand how you solved the problem. I have been using the Animated.View from `react-native-animated` which seems to be what's causing the issue. Could you show me what you did differently please in a code sample? It would be much appreciated. Thanks @anthlasserre !

**Comment by anthlasserre** [comment]
@worldlee78 I just made a bad **Animated** import... Not more.
For your issue have you tried with a shorter list ?

**Comment by flow-danny** [comment]
If I understand correctly, this can be fixed by upgrading to react-native-reanimated v2:
https://github.com/software-mansion/react-native-reanimated/issues/782#issuecomment-666223033

**Comment by flow-danny** [comment]
If I understand correctly, this can only be solved by using react-native-reanimated v2's `SharedValue` instead of `Animated.Node`.

**Comment by computerjazz** [comment]
While migrating to reanimated 2 is in the long-term plan, v2 currently has performance issues when rendering lots of nodes. Until these are addressed, this package (as well as `react-native-draggable-flatlist`) will stick to the v1 implementation, which is much more performant.

see:
https://github.com/software-mansion/react-native-reanimated/issues/1710
https://github.com/software-mansion/react-native-reanimated/issues/1635
https://github.com/software-mansion/react-native-reanimated/discussions/1632

**Comment by computerjazz** [comment]
I have an open PR for the Reanimated v2 migration. Can I get some folks here to help testing it out?

You can install via npm tag "beta" in `package.json`:

```
    "react-native-swipeable-item": "beta",
```

**Comment by Orange9000** [comment]
> I have an open PR for the Reanimated v2 migration. Can I get some folks here to help testing it out?
> 
> You can install via npm tag "beta" in `package.json`:
> 
> ```
>     "react-native-swipeable-item": "beta",
> ```

If `snapPointsRight` is not provided `clampedVal` becomes `-Infinity` which causes row to disappear from view when swiping.
I am using `2.0.0-beta.4`

**Comment by computerjazz** [comment]
@Orange9000 thanks for the feedback! I pushed the fix for empty snap points in `2.0.1`. 

Class components are going away so you won't be able to force update its ref in the same way. I'm curious why you need to resort to an imperative force update? As a last resort, you could change the `key` to achieve a hard update.
