### ISSUE TITLE
Unable to swipe consistently

### ISSUE THREAD

**Issue by amazingmarvin** [computerjazz/react-native-swipeable-item#2]
First of all, THANK YOU!  I've been looking for a way to have swipeable, pressable, reorderable lists since 2016 and this with `DraggableFlatList` is the closest I've come.

When I run the example in the ios simulator, I'm not able to swipe.  When I swipe outside the text, nothing happens.  When I try to swipe within the text, the `TouchableOpacity` lightens the text but I can't swipe.  Long press + drag and drop works fine!

Interestingly, if I press alt, then I can consistently swipe two rows at once (in opposite directions).

I'm currently unable to test on an iphone due to USB port troubles.  I ran on an Android physical device (release build) and had similar problems.  I'm able to get it to swipe perhaps 1 time in 10 (oneplus 6).

I tried updating as much as I could to the latest versions on iOS:

| Package | Version |
|---|---------|
| react-native | 0.59.10 |
| draggable-flatlist | 2.1.2 |
| swipeable-item | 1.1.1 |
| reanimated | 1.7.0 |
| gesture-handler | 1.5.3 |

The Android versions I'm testing are a bit older since I haven't upgraded to androidx yet:

| Package | Version |
|---|---------|
| react-native | 0.59.10 |
| draggable-flatlist | 2.1.2 |
| swipeable-item | 1.1.1 |
| reanimated | 1.2.0 |
| gesture-handler | 1.2.1 |

I see from the github README that you're indeed able to swipe from the ios simulator.  Are you on RN 0.61?  I will try upgrading to 0.61 next.  Which versions of draggable-flatlist, reanimated, and gesture-handler are you using?

**Comment by computerjazz** [comment]
This sounds like it may be an issue with gesture disambiguation -- the pan gesture handler of the list might be capturing swipe before the Swipeable item engages. Try adding a small `activationDistance` to the list and see if that helps:

```js
     <DraggableFlatList
          activationDistance={5}  // <--- add this
          keyExtractor={item => item.key}
          data={this.state.data}
          renderItem={this.renderItem}
          onDragEnd={({ data }) => this.setState({ data })}
        />
```
Reanimated 1.4+ is going to help a lot with performance -- I didn't know you could even install 1.7 on RN 59.

 I've been testing mainly using this expo snack: https://snack.expo.io/@computerjazz/swipetodelete-pkg

And also occasionally running a non-expo RN 61 test project.

**Comment by amazingmarvin** [comment]
After adding `activationDistance` it works great in the iOS simulator (still on RN 0.59)!  Thanks a lot.

**Comment by parnekov** [comment]
After adding activationDistance it works great in the iOS real device too.
