### ISSUE TITLE
where can i find the "./SwipeableItem" file in readme example

### ISSUE THREAD

**Issue by Yandamuri** [computerjazz/react-native-swipeable-item#20]
I am able to see  `SwipeableItem`  is imported from `"./SwipeableItem"` but not from `react-native-swipeable-item`  but i couldn't find "./SwipeableItem" .js file. 

Can some one help to find out this .js file?

**Comment by computerjazz** [comment]
whoops, that was a mistake, good catch!
should be `import SwipeableItem from "react-native-swipeable-item"`
