### ISSUE TITLE
Readme Example code

### ISSUE THREAD

**Issue by panda0603** [computerjazz/react-native-swipeable-item#21]
Hello, @computerjazz 

I am trying to implement swipeableItem with draggable flatlist. 

I have seen the code in the example in README, but seems like it is not the example code from the demo gif below: 

![Swipeable Item demo](https://i.imgur.com/fFCnQ0n.gif)

Where can I find the code for demo in gif? I would like to implement swipe gesture like in demo gif(which can be swiped using gesture instead of clicking button to open left or right in example code), which is different from the example code (currently doesn't swipe with gesture). 

Thanks!

**Comment by panda0603** [comment]
@computerjazz

**Comment by computerjazz** [comment]
Hi! Here's the snack: https://snack.expo.io/@computerjazz/swipeable-draggable-list
