### ISSUE TITLE
SwipeableItem consistently gets stuck between snap points

### ISSUE THREAD

**Issue by goleary** [computerjazz/react-native-swipeable-item#22]
**Describe the bug**
When I swipe quickly I am consistently able to get the item into a state where it is stuck at a point not specified in `snapPoints`

Android
![image](https://user-images.githubusercontent.com/16123225/105429281-f3cfb600-5c05-11eb-82b8-e9c045bbb270.png)
iOS
![image](https://user-images.githubusercontent.com/16123225/105429322-0813b300-5c06-11eb-8a01-46211dd947e0.png)

**Steps to reproduce the behavior:**
It's easy to see what I'm talking about using [this expo snack](https://snack.expo.io/).

**Platform & Dependencies**
Please list any applicable dependencies in addition to those below (react-navigation etc).

Platform (iOS/Android): Both
 React Native or Expo version: expo 40, react native 0.63.2
`react-native-reanimated` version: 1.13.0
`react-native-gesture-handler` version: 1.9.0

This has also been experienced on device for iOS & Android.

**Comment by computerjazz** [comment]
can you try downgrading `reanimated` to `1.9.0`? I've noticed some buggy behavior in later versions.

**Comment by goleary** [comment]
I am not able to repro the bug with the snack you provided. It seems to be much smoother on 1.9.0.

That said, it looks like downgrading `reanimated` in our project causes other issues so that doesn't seem to be an option for us.

**Comment by computerjazz** [comment]
I just incrementally bumped `reanimated` in that snack and it looks like all works well until `1.13.1`, so anything below that is likely fine. I'll dig into `1.13.1` soon and see if I can figure out what happened.

**Comment by computerjazz** [comment]
just published `1.5.3`, can you give it a shot?

**Comment by goleary** [comment]
Unreal, after upgrading I'm no longer able to get the item stuck (on both the expo snack and our project).

Thanks a TON for quickly getting to the bottom of it and getting the fix out!

**Comment by eric-om** [comment]
@computerjazz thanks for being so on top of this. The swipeable item works well in expo but when I install the actual app, it gets caught between my two snap points and the user needs to either swipe the item again or press the open button again.

```
"react-native-reanimated": "^1.13.2",
"react-native-gesture-handler": "^1.8.0",
"react-native-swipeable-item": "^1.5.4",
"react-native-draggable-flatlist": "^2.5.4",
```
