### ISSUE TITLE
Inconsistent behavior with multiple snap points

### ISSUE THREAD

**Issue by andrewnaeve** [computerjazz/react-native-swipeable-item#24]
**Describe the bug**
When multiple snap points are given, some snap points have difficulty catching.

**Steps to reproduce the behavior:**
Reproduction here: 
https://snack.expo.io/udWUkcb5K

1. drag a bit past the first snap point on the right hand side of the page. Observe the first point catch.
2. drag from the first point to the second. Observe a miss, and catch to the third snap point.
3. drag from the last snap point to the end of the row, observe the second snap point catch.

Expected behavior:
I would expect that dragging a bit past each snap point would catch the nearest point before it.

**Platform & Dependencies**
ios, web

Platform (iOS/Android):
 React Native or Expo version:
`react-native-reanimated` version: "~1.13.0"
`react-native-gesture-handler` version: "~1.8.0"

**Comment by computerjazz** [comment]
good catch, Thanks! Just released `1.5.7` with the fix.

I should have known not to trust JS default sort 😆
![Screen Shot 2021-04-30 at 9 41 34 ](https://user-images.githubusercontent.com/6730148/116726543-4accf000-a998-11eb-8f94-dbf4f731e542.png)
https://github.com/computerjazz/react-native-swipeable-item/commit/74de54998b28971d1b9829e6aa9d9a3dd63eafb0

**Comment by andrewnaeve** [comment]
Amazing, thanks!
