### ISSUE TITLE
Calling %s on the ref of an Animated component is no longer necessary. You can now directly use the ref instead. This method will be removed in a future release. e getNode()

### ISSUE THREAD

**Issue by Angelk90** [computerjazz/react-native-swipeable-item#28]
**Describe the bug**
Hi @computerjazz ,

I am receiving the following notice:

`%s: Calling %s on the ref of an Animated component is no longer necessary. You can now directly use the ref instead. This method will be removed in a future release. e getNode()`

Link: https://snack.expo.io/tmKuyAZBM

**Platform & Dependencies**

Platform (iOS/Android):
 React Native or Expo version: expo 41
`react-native-reanimated` version: ~2.1.0

**Comment by computerjazz** [comment]
this was coming from `react-native-draggable-flatlist`, now fixed
