### ISSUE TITLE
Feature proposal: full open

### ISSUE THREAD

**Issue by amazingmarvin** [computerjazz/react-native-swipeable-item#3]
One key piece of functionality for my app is to swipe fully open (e.g. lots of todo apps have swipe right to mark done).  So this would entail:

* `fullOpenRightThreshold` prop, meaning if the user swipe beyond this threshold (perhaps 0.5 means half the row width), then the row will open (i.e. animate all the way to the right).  Animation would ideally progress constantly at the speed of the user's swipe, unless this would take more than 80ms or something like that.  Special case: if the user swiped beyond the threshold and then changed their mind and swiped back toward the left to cancel.
* `onFullOpenRight` callback, called when the row has opened.
* luxury: `renderFullOpenUnderlayRight` - as the user approaches the threshold, this fades in over the `renderUnderlayRight` content.

Any thoughts on this?  Will be finishing my D&D work over the next weeks, and can attempt a PR (unless you already have something like this in the works).

**Comment by computerjazz** [comment]
I think that's a great idea. I would request some changes to the api though -- I think the use case is too specific as written. I would instead write it in terms of breakpoints, and the item would snap to the closest one. Something like `snapPointsLeft={[0, 100, deviceWidth]}`

Check out https://github.com/osdnk/react-native-reanimated-bottom-sheet `snapPoints` prop for one example of this.

As for the `render` methods I would omit them altogether and would leave this up to the developer --  the `percentOpen` animated value is already provided, so it should already be possible to render/fade/whatever using it.

**Comment by amazingmarvin** [comment]
Yeah that makes more sense.  Will update with progress.

**Comment by computerjazz** [comment]
I got inspired and took a crack at this -- it didn't end up being too painful, especially since the `reanimated-bottom-sheet` snap code was already written 😃. I think it's definitely the right direction, thanks for the suggestion.

Take a look and give it a try here: 
https://github.com/computerjazz/react-native-swipeable-item/blob/snapPoints/README.md

https://snack.expo.io/@computerjazz/swipetodelete-pkg

**Comment by amazingmarvin** [comment]
Oh awesome, thank you!  I checked out the expo and it looks great.  Will try it out on a device and let you know how it goes.

**Comment by amazingmarvin** [comment]
I tested it on my phone and it feels great there too.  One note: in the README it says `onChange` has `params.snapTo`, but it should be `params.snapPoint`.
