### ISSUE TITLE
Changing `snapPointsLeft` does not re-render `SwipableItem`

### ISSUE THREAD

**Issue by flow-danny** [computerjazz/react-native-swipeable-item#31]
## **Describe the bug**

Assigning `snapPointsLeft` from a `useState` variable only uses the initial value. Changing it does nothing..

## **Steps to reproduce the behavior:**

For our multi-language app we calculate the width of "Delete" in the user's language on first layout, then set a state variable.

```tsx
const [deleteButtonWidth, setDeleteButtonWidth] = useState(calculatedDeleteButtonWidth);

<Text
  onLayout={(layoutEvent: LayoutChangeEvent) => {
    const { width } = layoutEvent.nativeEvent.layout;
    const textWidth = Math.round(width);
    // The first underlay that is rendered updates the state: (otherwise CPU goes brrrr)
    if (textWidth !== deleteButtonWidth) {
      setDeleteButtonWidth((calculatedDeleteButtonWidth = textWidth));
    }
  }}>
  {t('i18n.message')}
</Text>
```

Which is used by `SwipableItem` to set `snapPointsLeft`:

```tsx
function renderAction(actionItem) {
  return (
    <SwipeableItem
      // Enable swiping only when deleteTextWidth has been calculated
      swipeEnabled={deleteButtonWidth != 0}
      renderUnderlayLeft={renderUnderlayLeft}
      snapPointsLeft={[deleteButtonWidth + 24]}
      renderOverlay={renderActionOverlay}
    />
  );
}
```

However, the *snap point is not updated* unless we resort to a workaround that forcibly re-renders the entire (long) list. The workaround is changing `key`:

```tsx
<DraggableFlatList
  // The key acts as a trigger to re-render the list when deleteTextWidth changes.
  // Without it, the SwipableItem underlays do not change size.
  // This is probably a bug in how `snapPointsLeft` is handled.
  key={deleteButtonWidth}
  renderItem={renderAction}
  ...
```

## Platform & Dependencies**

Platform: iOS & Android
 React Native or Expo version: Expo 41
`react-native-reanimated` version: 2.1.0
`react-native-gesture-handler` version: 1.10.3

**Comment by computerjazz** [comment]
fixed in v2.0.0. see snack for demo: https://snack.expo.dev/@computerjazz/swipeable-draggable-list
![rnsi-snapPoints_fix](https://user-images.githubusercontent.com/6730148/141826115-ca476292-3b72-4187-a4ee-02cf754c0689.gif)
