### ISSUE TITLE
Freeze some elements from dragging

### ISSUE THREAD

**Issue by AishwaryaSurana** [computerjazz/react-native-swipeable-item#33]
Is it possible to allow drag of few elements
say I have draggableFlatList from 1-10
I want to drag first 5 elements and remaining elements must be non-draggable.

Is it possible?

**Comment by computerjazz** [comment]
This should be a question on the `react-native-draggable-flatlist` repo, but the short answer is, just don't call `drag()` on elements that shouldn't be draggable.
