### ISSUE TITLE
Please support `react-native-reanimated` 2

### ISSUE THREAD

**Issue by Pix-00** [computerjazz/react-native-swipeable-item#34]
### Describe the problem
Please support `react-native-reanimated` 2.
Also please update peer dependency `react-native` to 0.65 (or >=0.60 etc.).

### Platform & Dependencies
Platform (iOS/Android): Android
 React Native or Expo version: 0.65.1
`react-native-reanimated` version: 2.2.0
`react-native-gesture-handler` version: 1.10.3

**Comment by jcarioti** [comment]
We're seeing issues related to these swipe menu items after upgrading to reanimated v2. In particular, swiping open a menu item doesn't always call `onChange` and the item immediately snaps closed. Occasionally, the swipe works, but it seems very broken.

**Comment by Pix-00** [comment]
Thanks for answering.
