### ISSUE TITLE
Package does not support react-native-reanimated@2.3.1

### ISSUE THREAD

**Issue by goleary** [computerjazz/react-native-swipeable-item#40]
**Describe the bug**
This package results in TS errors when used with `react-native-reanimated@2.3.1`.

When I pin `react-native-reanimated` to `2.2.x` things work as expected.

**Steps to reproduce the behavior:**

- install latest version of this package with dependencies
- run tsc (may require imporing of the package)

**Platform & Dependencies**
Please list any applicable dependencies in addition to those below (react-navigation etc).

Platform (iOS/Android): iOS
 React Native or Expo version: 0.66.0
`react-native-reanimated` version: 2.3.1
`react-native-gesture-handler` version: 2.1.0

**Additional context**

These are the errors we see
```
node_modules/react-native-swipeable-item/src/index.tsx:74:38 - error TS2694: Namespace 'Animated' has no exported member 'WithSpringConfig'.

74   animationConfig?: Partial<Animated.WithSpringConfig>;
                                        ~~~~~~~~~~~~~~~~

node_modules/react-native-swipeable-item/src/index.tsx:107:32 - error TS2694: Namespace 'Animated' has no exported member 'WithSpringConfig'.

107   const springConfig: Animated.WithSpringConfig = {
                                   ~~~~~~~~~~~~~~~~

node_modules/react-native-swipeable-item/src/index.tsx:189:45 - error TS2345: Argument of type 'boolean | undefined' is not assignable to parameter of type 'boolean'.
  Type 'undefined' is not assignable to type 'boolean'.

189           runOnJS(resolvePromiseIfFinished)(isFinished);
                                                ~~~~~~~~~~

node_modules/react-native-swipeable-item/src/index.tsx:203:45 - error TS2345: Argument of type 'boolean | undefined' is not assignable to parameter of type 'boolean'.

203           runOnJS(resolvePromiseIfFinished)(isFinished);
                                                ~~~~~~~~~~

node_modules/react-native-swipeable-item/src/index.tsx:215:43 - error TS2345: Argument of type 'boolean | undefined' is not assignable to parameter of type 'boolean'.

215         runOnJS(resolvePromiseIfFinished)(isFinished);
                                              ~~~~~~~~~~

**Comment by computerjazz** [comment]
Hm that is annoying—looks like Reanimated moved WithSpringConfig off the default export in 2.3.0: https://github.com/software-mansion/react-native-reanimated/pull/2451

So that means if I update the import to use the named import it will break for anyone using reanimated lower than 2.3.0, and if i use the default it will be broken for anyone greater than 2.3.0

**Comment by goleary** [comment]
That is annoying. It seems like that change should only have been made as a part of a major (breaking) version release? Perhaps it's worth opening an issue on their repo to see if they'd release a patch to rectify the original behavior?

I'd open it myself, but I think you better understand what's needed & how to communicate it @computerjazz

It looks like that's one of two issues at play here. The other being a mismatch of types (`boolean` vs `boolean | undefined`) passed to the function returned by  `runOnJS()`.

Thanks for looking into these!

**Comment by computerjazz** [comment]
everything is moved to the new import now
