### ISSUE TITLE
Add custom props to RowItem

### ISSUE THREAD

**Issue by flpmko** [computerjazz/react-native-swipeable-item#44]
**Describe the bug**
This is not a bug, it's an issue I don't know how to solve, so I thought maybe the author of this great package would know the solution.

I'm usig the SwipableItem in DraggableFlatList. I did everything according to the demo, everything works as it should. I'm able to swipe and drag. However, I want to add a custom onPress function to the list item, so I can navigate to the next screen when I press the list item. (I'm using react-navigation). For this to work, I need to pass a navigation prop to the RowItem component, but I couldn't figure out how. The TypeScript restrictions will not let me add an onPress or navigation prop. Is there a way I can pass this prop to the RowItem so I can use it in SwipeableItem?

I tried wrapping the RowItem in TouchableOpacity like shown below, so I can call the onPress event on the TouchableOpacity, but it didn't recognize the touch on the TouchableOpacity component. The SwipeableItem kept working as it should, but the onPress event on the TouchableOpacity wasn't called.

```js
const renderItem = useCallback((params: RenderItemParams<Item>) => {
    return (
    <TouchableOpacity onPressIn={() => console.log('pressin')} onPress={() => console.log('press')}>
      <RowItem {...params} itemRefs={itemRefs} />
    </TouchableOpacity>)
  }, []);
// no console logs were logged
```

**Steps to reproduce the behavior:**
I tried adding an onPress prop to the <RowItem/> in renderItem() method. In the demo, it's line 56.

```js
const renderItem = useCallback((params: RenderItemParams<Item>) => {
    return <RowItem {...params} itemRefs={itemRefs} onPress={() => myFunction()}/>
  }, []);
// Property 'onPress' does not exist on type 'IntrinsicAttributes & RowItemProps
```

Here is my [repo](https://github.com/flpmko/spevnik-mobile-app).
And the specific [file](https://github.com/flpmko/spevnik-mobile-app/blob/1f7dd151a2a571405bcd26b834694cf5f90ebe0b/app/components/playlist/PlaylistDetail.tsx), line 121.

**Platform & Dependencies**
Platform (iOS/Android): iOS and Android
 React Native version: 0.64.3
 Expo version: 44.0.6
`react-native-reanimated` version: 2.3.3
`react-native-gesture-handler` version: 2.1.3
`react-navigation/native` version: 6.0.8
`react-navigation/native-stack` version: 6.5.2

**Comment by computerjazz** [comment]
Hm I think you may be confusing a few different components, please take another look at the example in the README: https://github.com/computerjazz/react-native-swipeable-item#example

The `RowItem` in the example doesn't come from within this package, it's defined in the example itself. If you copied and pasted the example, you can also edit `RowItem` props, or completely rewrite it.

Yours could look something like this:
```ts
type RowItemProps = {
  item: Item;
};

function RowItem({ item, drag }: RowItemProps) {

  const navigation = useNavigation()

  return (
      <SwipeableItem
        key={item.key}
        item={item}
        renderUnderlayLeft={() => <MyCustomUnderlayLeft />}
        renderUnderlayRight={() => <MyCustomUnderlayRight />}
        snapPointsLeft={[175]}
        snapPointsRight={[175]}
      >
          <TouchableOpacity onLongPress={drag} onPress={() => navigation.navigate("some-other-route")}>
            <Text style={styles.text}>{"EXAMPLE"}</Text>
          </TouchableOpacity>
      </SwipeableItem>
  );
}
```

**Comment by flpmko** [comment]
Thank you very much for your answer!

**Comment by flpmko** [comment]
Ok, so with your help and with help of similar issue on stackoverflow, I was able to achieve my goal.

As @computerjazz suggested, I changed the RowItem props. I also had to annotate useNavigation(), for type checking. On how to do this, I followed react-navigation [documentation](https://reactnavigation.org/docs/typescript/#annotating-usenavigation) and [this issue](https://stackoverflow.com/questions/68739045/how-to-properly-type-usenavigation-in-react-navigation) on stackoverflow.

Now my code looks like this:

```js
type RowItemProps = {
  item: Item;
  drag: () => void;
  itemRefs: React.MutableRefObject<Map<any, any>>;
};

function RowItem({ item, itemRefs, drag }: RowItemProps) {
  const { theme } = React.useContext(UserContext);
  type StackParamList = {
    SongDetail: { song: Item }
}

type NavigationProps = NativeStackNavigationProp<StackParamList>;
  const navigation = useNavigation<NavigationProps>();

// ...

return(
<ScaleDecorator>
    <SwipeableItem>
        <View >
           <TouchableOpacity onLongPress={drag} onPress={() => navigation.navigate("SongDetail", {song: item})} >

                {/* ... */}

           </TouchableOpacity>
        </View>
    </SwipeableItem>
</ScaleDecorator>
)
```

And now when I press the RowItem, I can navigate to the desired screen with props I need. And I'm still able to drag and swipe the RowItem. 🎉
