### ISSUE TITLE
onPress not working

### ISSUE THREAD

**Issue by amazingmarvin** [computerjazz/react-native-swipeable-item#5]
**Describe the bug**

I am not able to use `onPress` inside my `SwipeableItem` overlays.  I started with the demo list from the README and added a `onPress` in addition to the `onLongPress`, but it's never called.

**Steps to reproduce the behavior:**

Here's a [demo project](https://github.com/amazingmarvin/SwipeableItemDemo).  Long pressing to reorder works.  But when you do a regular press it should change all the item texts to "An item was pressed".  Instead nothing happens.

**Platform & Dependencies**
None in the demo project.

Platform (iOS/Android):
 React Native or Expo version: 0.61.5
`react-native-reanimated` version: 1.7.0
`react-native-gesture-handler` version: 1.5.6

**Additional context**

This is important functionality since you might want to show a new list when tapping, edit the item, etc.  So primary action would be through tapping and secondary action(s) through swipes.  My first idea for a workaround is to make a new component that extends TouchableOpacity or TouchableWithoutFeedback and uses onPressIn and onPressOut with some timers (although I would have guessed that's exactly how TouchableWithoutFeedback is implemented).  Or maybe to just act on onPressOut (if onDragBegin was never called).  Have to investigate which events are called and when.

Do you have any idea why it's not working?  Seems like it might be nice to document this if a workaround is possible.  And if a workaround is possible then it would make sense to me to integrate it into the library and add onPress and onLongPress directly to the SwipeableItem.

**Comment by computerjazz** [comment]
Thanks for the detailed bug report. This is actually an issue with `react-native-draggable-flatlist` and `react-native-gesture-handler` `TapGestureHandler`, documented in https://github.com/computerjazz/react-native-draggable-flatlist/issues/120.

I have what I believe is the fix on master in that repo. I will release after a bit more testing and verification.

The demo project is useful, but even more useful (and less effort for everyone) would be a Snack: https://snack.expo.io/

**Comment by amazingmarvin** [comment]
OK, thanks for the info.  This is indeed on Android (haven't tested on iOS yet).  I will try installing react-native-draggable-flatlist from master and let you know how it goes.

In my additional experiments I saw that onPressOut is (usually) not being called at all.

Will make a Snack in the future!  Sorry about the inconvenience.

**Comment by computerjazz** [comment]
No worries! If you install from `master` you'll probably need to edit `package.json` within the DraggableFlatlist node modules folder to point to the projects `src` folder instead of the built version, which isn't checked in.

Here's a snack I created to test the changes that are now on master -- you may be able to drop your code in to see if it fixes the issue: https://snack.expo.io/BJ!3zmkXL , just be sure to keep the link to the local DraggableFlatlist code and not the npm version .

**Comment by computerjazz** [comment]
Removed TapGestureHandler in react-native-draggable-flatlist  2.3.0, please upgrade let me know if the onPress issue is fixed.

**Comment by amazingmarvin** [comment]
OK, sorry about the delay and thanks for letting me know about the new version!  `onPressIn`, `onPress`, and `onLongPress` work as expected, whereas `onPressOut` is never called.  This is fine for me since `onPress` is what I really need.
