### ISSUE TITLE
Swipeable-item not swiping but draggable flatlist works

### ISSUE THREAD

**Issue by robgraeber** [computerjazz/react-native-swipeable-item#53]
I already solved my problem, posting here in case anyone encounters the same thing. I had `react-native-draggable-flatlist` working correctly but `react-native-swipeable-item` wasn't swiping at all.

Turns out my babel plugins were misordered, solution was to ensure `react-native-reanimated/plugin` is always at the end of the plugins list.

```module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: [
      ...,
      'react-native-reanimated/plugin',
    ],
  };
};
```

**Comment by computerjazz** [comment]
Thanks, I'm going to close this issue since it's not an issue with the package, but I'm glad it'll be searchable for others!
