### ISSUE TITLE
Example causes CPU to go to max

### ISSUE THREAD

**Issue by joshbuddy** [computerjazz/react-native-swipeable-item#54]
Hey y'all. Really appreciate these libraries!

I've been trying to get the example to work but unfortunately when I run it it causes the CPU to go to 200% in the simulator. To try to isolate the issue I've created a brand new expo project and copied the example, but it still causes the CPU to spike after swiping the first item.

I've included the project.json and a video showing the behavior below.

Any guidance on how to understand what's happening here? Thanks

### `Package.json`
```
{
  "name": "test-proj",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~46.0.6",
    "expo-status-bar": "~1.4.0",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-native": "0.69.4",
    "react-native-draggable-flatlist": "^3.1.2",
    "react-native-gesture-handler": "~2.5.0",
    "react-native-reanimated": "^2.9.1",
    "react-native-swipeable-item": "^2.0.7",
    "react-native-web": "~0.18.7"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@types/react": "~18.0.14",
    "@types/react-native": "~0.69.1",
    "typescript": "~4.3.5"
  },
  "private": true
}
```

### Video

https://user-images.githubusercontent.com/8898/184342414-5a917ab5-d890-4603-b0a4-6c8e16522829.mp4

**Comment by joshbuddy** [comment]
Did a little more testing and this is a regression in 2.0.7, 2.0.6 works correctly.

**Comment by GabrielDierks** [comment]
I can confirm it is working on 2.0.6! But I have the same issue with 2.0.7

The issue seems to be caused by this function:

`if (open) {
	[...itemRefs.current.entries()].forEach(([id, ref]) => {
		if (id !== item.id && ref) ref.close();
});
`

**Comment by computerjazz** [comment]
So, there are two things going on there, both should be fixed in `2.0.8` -- 
- I named the `open` parameter in `onChange` poorly as it is an enum. It is now renamed to `openDirection`. It shouldn't be checked for truthiness since it is always a string value.
- `onChange` was being called too often.

https://github.com/computerjazz/react-native-swipeable-item/releases/tag/v2.0.8

**Comment by joshbuddy** [comment]
Thank you so much. Everything works great with `2.0.8`.

**Comment by jmif** [comment]
We're seeing this in 2.0.8 still, the app becomes progressively slower especially after swiping.  We ended up rolling back to 2.0.6 and the issue was resolved.  I've confirmed that we're properly checking open and that onChange is not being called frequently in 2.0.8.  We're on reanimated 2.9.1.

**Comment by computerjazz** [comment]
@jmif If you can provide a repro via an expo snack I'll take a look.
