### ISSUE TITLE
Does react-native-swipeable-item play well with react-native-gesture-handler/Swipeable and which one should I start with?

### ISSUE THREAD

**Issue by kopax** [computerjazz/react-native-swipeable-item#6]
Hello, I am testing your snack in #1  and it seems it doesn't work on the web. 

I'd like to know what is this project compare to https://github.com/software-mansion/react-native-gesture-handler/blob/master/docs/component-swipeable.md 

Both are very recent examples and I have read this article https://medium.com/p/bd7d66085aee 

The `react-native-gesture-handler` versions seems to be more close to what I'd like to achieve since it also work on the web and as no bounce and better feeling for the user.

I want to have 3 lists:

- list
  - swipe left to delete after a timeout (or tap to cancel)
  - swipe right to add to favorite after a timeout (or tap to cancel)
- delete list
  - swipe left to remove from delete list after a timeout (or tap cancel)
  - swipe right to add to favorite and remove from delete list after a timeout  (or tap to cancel)
- bookmark list
  - swipe left to remove from bookmark list after a timeout (or tap cancel)

So far the example in https://github.com/software-mansion/react-native-gesture-handler/blob/master/docs/component-swipeable.md  only needs to add the delete feature.

Any idea how I could do and do you have any thought about this?

**Platform & Dependencies**

I want to build this for iOS, Android and web.

Expo version: SDK 36
`react-native-reanimated` version: 1.4.0
`react-native-gesture-handler` version: 1.6.0

**Comment by computerjazz** [comment]
Yep, they're similar.
I began building mine as the subject of the tutorial you linked, and decided I liked the result, so I published it. 
I don't have any strong opinions -- choose whichever one you like better!

**Comment by kopax** [comment]
Thanks a lot for both answers. I decided to go with the Swipeable from gesture handler package. I have noted that with a draggable need, your package would be a better start.

Thanks a lot for your sharings. 

Dimitri
