### ISSUE TITLE
Production demo

### ISSUE THREAD

**Issue by amazingmarvin** [computerjazz/react-native-swipeable-item#7]
@computerjazz We launched to production this week and users are very happy.  Thanks so much again for this library!

Here's a gif demonstrating our use of the library.  Feel free to add to README if you want a product demo there.

<img src="https://user-images.githubusercontent.com/35364886/77653501-10f91100-6f70-11ea-9fb5-c48ad86d17b7.gif" width="250" />

**Comment by computerjazz** [comment]
Thanks for sharing! Is it in the app store? Would love to check it out.

**Comment by amazingmarvin** [comment]
@computerjazz Yes, it's [here](https://apps.apple.com/app/amazing-marvin-on-the-go/id1314511546?l=en).  And if you like it (or the web app which has more features and onboarding), email support (write `@mark` in the title) and I'll be happy to give you a free account :).
